iohub.util.exception_tools.ioHubError
=====================================

.. currentmodule:: iohub.util.exception_tools

.. autoexception:: ioHubError